### PR TITLE
Pin pyyaml <6

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
@jchodera assuming this builds fine, this will fix 
https://github.com/conda-forge/yank-feedstock/issues/1
https://github.com/choderalab/yank/issues/1264

I will do a more complete fix on the next yak release

**Comment by lilyminium** [comment]
Just checking in, it would be great to see this update in production! I keep forgetting to pin the yank version myself, and OpenFF Evaluator happily runs for 8 hours before failing here and deleting all intermediate data 😭

**Comment by jchodera** [comment]
@mikemhenry Can you help get this out if it's ready?

**Review by jchodera — APPROVED** [review]
Approved! Thanks!

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
@jchodera @jaimergp could one of you merge this in (after CI passes, you should be able to add the auto merge label)? I had forgotten about it, but it is still needed. I've added myself to the maintainers list for future PRs.

**Review by jchodera — APPROVED** [review]
Thanks, @mikemhenry, and apologies for the delay! 
Feel free to ping me by slack or email if I'm blocking on this in future.

**Pull request merged**
